#Add the following policy (for Allowing SSL Requests only) to the resource.yml file
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref BucketName
      PolicyDocument: 
       Version: '2012-10-17'
       Statement:
       - Sid: AllowSSLRequestsOnly
         Action: s3:*
         Effect: Deny
         Resource:
         - arn:aws:s3:::DOC-EXAMPLE-BUCKET
         - arn:aws:s3:::DOC-EXAMPLE-BUCKET/*
         Condition:
           Bool:
             aws:SecureTransport: 'false'
